schemaVersion: 2.2.0
metadata:
  name: elite-carrier-manager
  version: 1.0.0
  description: "Dev Spaces environment for Fleet Carrier Upkeep Hub"
  tags: ["Python", "Flask", "SQLite", "OpenShift"]

projects:
  - name: elite-carrier-manager
    git:
      remotes:
        origin: "https://github.com/borrel/elite-carrier-manager/"

components:
  # The unified environment runtime block containing the Python stack tools
  - name: python-runtime
    container:
      image: registry.access.redhat.com/ubi9/python-39:1-1789345358
      args: ['tail', '-f', '/dev/null']
      mountSources: true
      endpoints:
        - name: https-python
          targetPort: 8080
          protocol: https
        - exposure: none
          name: debug
          targetPort: 5858
      env:
        - name: DEBUG_PORT
          value: '5858'

commands:
  - id: pip-install-requirements
    exec:
      commandLine: pip install -r requirements.txt
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: build
        isDefault: true
      component: py
  - id: run-app
    exec:
      commandLine: 'python app.py'
      workingDir: ${PROJECT_SOURCE}
      component: py
      group:
        kind: run
        isDefault: true
  - id: run-scheduler
    exec:
      commandLine: 'python scheduler.py'
      workingDir: ${PROJECT_SOURCE}
      component: py
      group:
        kind: run
        isDefault: false
  - id: debug-py-app
    exec:
      commandLine: 'pip install debugpy && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} app.py'
      workingDir: ${PROJECT_SOURCE}
      component: py
      group:
        kind: debug
  - id: debug-py-scheduler
    exec:
      commandLine: 'pip install debugpy && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} scheduler.py'
      workingDir: ${PROJECT_SOURCE}
      component: py
      group:
        kind: debug